# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Global Dependencies
	parchment_mc_version=1.21
	parchment_version=2024.07.07
	coroutil_version=1.3.8
	libbulletjme_version = 17.4.0

# Fabric Properties
    # check these on https://fabricmc.net/develop
	minecraft_version=1.21
    yarn_mappings=1.21+build.9
    loader_version=0.15.11

# Fabric Dependencies
	fabric_version=0.100.7+1.21

# Forge Properties
	forge_version=51.0.29
	minecraft_version_range=[1.21,1.22)
	forge_version_range=[51,)
	loader_version_range=[51,)

# Neoforge Properties
	neo_version=21.0.167
	neo_version_range=[21.0.0-beta,)
	neo_loader_version_range=[4,)

# Mod Properties
	mod_id = weather2
	mod_name=Weather2
	mod_version = 1.21.0-2.8.5
	mod_description=Speeeeeeen
	maven_group = com.corosus.weather2
	archives_base_name = weather2
	mod_authors=Corosus
	mod_license=All Rights Reserved

ltminigames_version=0.1.0-alpha+1140-gha